### ISSUE TITLE
Cant install server

### ISSUE THREAD

**Issue by Mega-Bits** [vinanrra/Docker-Satisfactory#23]
Hello,

i tried to install this container using docker-compose, but when i try to install the server itself it fails. I am on Ubuntu 22.04 with docker version 24.0.7

docker-compose.yml

```
version: '2'
services:
  sfserver:
    image: vinanrra/satisfactory-server:latest
    container_name: sfserver
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #entrypoint: /bin/bash
    environment:
      - START_MODE=0 # Change between START MODES
      - PUID=0 # Remember to use same as your user
      - PGID=0 # Remember to use same as your user
      - TimeZone=Europe/Berlin
      - TEST_ALERT=NO
      - BACKUP=YES # Backup server at 5 AM
      - MONITOR=YES # Keeps server up if crash
      - VERSION=public #experimental # Change between server versions
    volumes:
      - /opt/docker/gameserver/satisfactory2/ServerFiles:/home/sfserver/serverfiles/ # Optional, serverfiles
      - /opt/docker/gameserver/satisfactory2/log:/home/sfserver/log/ # Optional, logs
      - /opt/docker/gameserver/satisfactory2/backups:/home/sfserver/lgsm/backup/ # Optional, backups
      - /opt/docker/gameserver/satisfactory2/LGSM-Config:/home/sfserver/lgsm/config-lgsm/sfserver # Optional, LGSM-Config
      - /opt/docker/gameserver/satisfactory2/SavesGames:/home/sfserver/.config/Epic/FactoryGame/Saved/SaveGames # Satisfactory Saves
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    #restart: none #NEVER USE WITH START_MODE=4 or START_MODE=0
```

Console log:
 ```
   =======================================================================

    USER INFO:

    UID: 0

    GID: 0

    MORE INFO:

    If you have permission problems remember to use same user UID and GID.

    Check it with "id" command

    If problem persist check:

    https://github.com/vinanrra/Docker-Satisfactory/blob/master/README.md

    =======================================================================

    

 * Starting periodic command scheduler cron        
[ OK ]

[INFO] It seems to be the first installation, making preparations...

fetching GitHub core_functions.sh...ERROR

fetching Bitbucket core_functions.sh...FAIL

./sfserver: line 129: core_exit.sh: command not found

./sfserver: line 387: fn_fetch_config: command not found

copying _default.cfg...cp: cannot stat '/home/sfserver/lgsm/config-default/config-lgsm/sfserver/_default.cfg': No such file or directory

FAIL

[INFO] Selection version public to install

grep: /home/sfserver/lgsm/config-lgsm/sfserver/sfserver.cfg: No such file or directory

[INFO] Already on public

[INFO] Starting server installation

fetching GitHub core_functions.sh...ERROR

fetching Bitbucket core_functions.sh...FAIL

./sfserver: line 129: core_exit.sh: command not found

./sfserver: line 387: fn_fetch_config: command not found

copying _default.cfg...cp: cannot stat '/home/sfserver/lgsm/config-default/config-lgsm/sfserver/_default.cfg': No such file or directory

FAIL

[INFO] The server have been installed.

[INFO] Activated automatic backup

[INFO] Activated server monitoring, automatic restart if crash
```

Any ideas why this is happening?
