### ISSUE TITLE
Updating server wipes everything

### ISSUE THREAD

**Issue by TheGreatestJannet** [vinanrra/Docker-Satisfactory#6]
Hello I have tried updating my server to the latest version using launch mode 2 and 3 and on both occasions everything has been wiped and it is like it is a new server. Is there any way to prevent this and update without losing everything?

**Comment by vinanrra** [comment]
Could you send me the command that you used or the docker-compose?

**Comment by TheGreatestJannet** [comment]
Here is what I'm using:
```
version: '2'
services:
  sfserver:
    image: vinanrra/satisfactory-server
    container_name: sfserver
    environment:
      - START_MODE=1 #Change between START MODES
      - PUID=1003 # Remember to use same as your user
      - PGID=1003 # Remember to use same as your user
      - TimeZone=Europe/London
      - TEST_ALERT=NO
      - BACKUP=YES # Backup server at 5 AM
      - MONITOR=YES # Keeps server up if crash
    volumes:
      - ./ServerFiles:/home/sfserver/serverfiles/ #Optional, serverfiles
      - ./log:/home/sfserver/log/ #Optional, logs
      - ./backups:/home/sfserver/lgsm/backup/ #Optional, backups
      - ./LGSM-Config:/home/sfserver/lgsm/config-lgsm/sfserver # Optional, LGSM-Config
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    restart: unless-stopped #NEVER USE WITH START_MODE=4 or START_MODE=0

```
